{
  "hash": "23db1405a297ec13797e2d10a40068ce",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: $k$-Means Clustering\njupyter: python3\n---\n\n\n\n# Victorian England\n\n\n## 1854 Cholera Outbreak\n\n[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/tools4ds/DS701-Course-Notes/blob/main/ds701_book/jupyter_notebooks/06-Clustering-I-kmeans.ipynb)\n\n:::: {.columns }\n\n::: {.column width=\"40%\"}\n![London cholera outbreak](./figs/Punch-A_Court_for_King_Cholera.png){width=400}\n^[Public Domain, https://commons.wikimedia.org/w/index.php?curid=680455]\n:::\n\n::: {.column width=\"60%\" .incremental}\n- There was a horrific cholera outbreak in **1854** Soho, London.\n- Common wisdom at the time was that disease spread by breathing \"foul air\" (miasma).  \n- The London sewer system had not yet reached Soho.  \n- Most homes had cesspits under the floor, which often overflowed.\n- \"Night Soil Men\" would regularly collect and sell to farmers or dump in the Thames.\n:::\n\n::::\n\n## John Snow\n\n:::: {.columns }\n\n::: {.column width=\"60%\" .incremental}\n- John Snow, a local physician, extensively studied the patterns of illness across Soho due to cholera.\n- In the course of his studies, his attention was drawn to one neighborhood around Broad Street.\n- In 10 days, 500 people in the area died. \n:::\n\n::: {.column width=\"40%\"}\n![John Snow](./figs/L06-John-Snow-Portrait.png)\n:::\n\n::::\n\n## John's Snow Map\n\n:::: {.columns }\n\n::: {.column width=\"60%\"}\n![London cholera outbreak](figs/L6-Snow-cholera-map-1.png){width=500px}\n:::\n\n::: {.column width=\"40%\" .incremental}\n- In uncovering the source of this outbreak, Snow prepared this map.\n- From this map he could clearly see the deaths were clustered around an area.\n- The neighborhood was all served by a water pump on Broad St.\n- The pump handle was removed and illnesses decreased dramatically.\n\n::: {.fragment}\n![Broad St. water pump](./figs/L6-John_Snow_memorial_and_pub.png){width=180}\n:::\n\n:::\n\n::::\n\n---\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n![J. Snow Book](figs/L06-snow-book-cover.png){height=500}\n:::\n::: {.column width=\"50%\" .incremental}\n- He later published his results^[By John Snow - Published by C.F. Cheffins, Lith, Southhampton Buildings, London, England, 1854 in Snow, John. On the Mode of Communication of Cholera, 2nd Ed, John Churchill, New Burlington Street, London, England, 1855.]\n- Results from the cluster map.\n- Results from a double blind study of two neighborhoods drawing water upriver and downriver of the polluted portion of the Thames.\n- Other anecdotes of visitors to Soho, etc.\n:::\n::::\n\n::: {.content-hidden when-profile=\"slides\"}\n## References and Further Reading \n\nImages and information taken from [wikipedia](https://en.wikipedia.org/wiki/1854_Broad_Street_cholera_outbreak), \n[National Library of Medicine](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7150208/) and the \n[Internet Archive](https://archive.org/details/b28985266/page/n3/mode/2up) and\n[MSU's John Snow Archive](https://johnsnow.matrix.msu.edu/).\n\nJohn Snow's original data is recreated [here](https://blog.rtwilson.com/john-snows-cholera-data-in-more-formats/).\n:::\n\n# Clustering\n\n## Clustering\n\n::: {.fragment}\nClustering is a very important way of discovering __structure__ in data.\n:::\n\n::: {.fragment}\nIt is so important because it is __common__ for data to show clusters.\n:::\n\n::: {.incremental}\n* Locations where millionaires live\n* The number of hours people work each week\n* Demographics (\"soccer parents\", \"bored retirees\", \"unemployed millenials\", etc)\n:::\n\n::: {.content-hidden when-profile=\"web\"}\n## Clustering Continued\n:::\n\n::: {.incremental}\n* We can often simplify or compress our data if we recognize the existence of clusters.\n* Further, we can often interpret clusters by assigning them labels.\n* However, note that these categories or \"labels\" are assigned __after__ the fact.\n* And, we may __not__ be able to interpret clusters or assign them labels in some cases.\n* That is, clustering represents the first example we will see of __unsupervised__ learning.\n:::\n\n## Supervised vs Unsupervised\n\n__Supervised__ methods:  Data items have labels, and we want to learn a function that correctly assigns labels to new data items.\n\n__Unsupervised__ methods:  Data items do not have labels, and we want to learn a function that extracts  important patterns from the data.\n\n## Applications of Clustering\n\n* Image Processing\n    * Cluster images based on their visual content.\n    * Compress images based on color clusters.\n* Web Mining\n    * Cluster groups of users based on webpage access patterns.\n    * Cluster web pages based on their content.\n* Bioinformatics\n    * Cluster similar proteins together (by structure or function).\n    * Cluster cell types (by gene activity).\n* And many more ...\n\n## The Clustering Problem\n\nWhen we apply clustering, what problem are we trying to solve?\n\n::: {.fragment}\nWe will answer this question informally at first, then apply formal criteria.\n:::\n\n::: {.fragment .fade-in}\nInformally, a __clustering__ is:\n    \n> a grouping of data objects, such that the objects within a group are similar (or near) to one another and dissimilar (or far) from the objects in other groups.\n\n(keep in mind that if we use a distance function as a dissimilarity measure, then \"far\" implies \"different\")\n:::\n\n::: {.content-hidden when-profile=\"web\"}\n## The Clustering Problem, continued\n:::\n\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nSo we want our clustering algorithm to:\n\n* <font color = \"blue\">minimize</font> intra-cluster distances.\n* <font color = \"red\">maximize</font> inter-cluster distances.\n:::\n::: {.column width=\"50%\"}\n![](figs/L06-clustering-1.png){width=500 fig-align=\"center\"}\n:::\n::::\n\n\n## The Clustering Problem, continued\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nHere are the basic questions we need to ask about clustering:\n\n::: {.incremental}\n* What is the right kind of <font color = \"blue\">\"similarity\"</font> to use?\n* What is a <font color=\"blue\">*good* partition</font> of objects?\n    * i.e., how is the quality of a solution measured?\n* <font color = \"blue\">How to find</font> a good partition?\n    * Are there efficient algorithms?  \n    * Are there algorithms that are guaranteed to find good clusters?\n:::\n:::\n::: {.column width=\"50%\"}\n![](figs/L06-clustering-1.png){width=500 fig-align=\"center\"}\n:::\n::::\n\n\n::: {.content-hidden when-profile=\"web\"}\n## The Clustering Problem, continued\n:::\n\nNow note that even with our more-formal discussion, the criteria for deciding on\na \"best\" clustering can still be ambiguous.\n    \n![](figs/L06-clustering-2.png){width=600 fig-align=\"center\"}\n\n::: {.fragment}\nLater, we will discuss hierarchical clustering which let's us consider clustering\nat multiple scales.\n:::\n\n## Partitional Clustering\n\n:::: {.columns}\n::: {.column width=\"50%\"}\nFor now, we'll focus on __partitional__ clustering. \n\nPoints are divided into a set of __non-overlapping__ groups:\n\n* Each object belongs to __one__, and only one, cluster. (mutually exclusive)\n* The set of clusters covers all the objects. (exhaustive)\n\nWe are going to assume for now that the number of clusters, $k$, is given in advance.\n:::\n::: {.column width=\"50%\"}\n![](figs/L06-partitional-clustering.png){width=600 fig-align=\"center\"}\n:::\n::::\n\n# The $k$-means Algorithm\n\n## Assumptions\n\nNow, we are ready to state our first formalization of the clustering problem.\n\nWe will assume that \n\n* data items are represented by points in $d$-dimensional space, $\\mathbb{R}^d$, i.e.,  has $d$ features,\n* the number of points, $N$, is given, and\n* the number of clusters $K$ is given.\n\n## Minimizing a Cost Function\n\nFind $K$ disjoint clusters $C_k$, each described by points $c_1, \\dots, c_K$\n(called <font color=\"blue\"> _centers_, _centroids_,</font> or <font color = \"blue\"> _means_)</font>\nthat minimizes\n\n$$\n\\underset{C_1, \\dots, C_K}{\\arg\\min} \\hspace{1em} \\sum_{k=1}^K \\hspace{1em} \\sum_{x\\in C_k} \\Vert x-c_k\\Vert^2. \n$$\n\n* The _Within-Cluster Sum of Squares_ (WCSS) or the _Inertia_ of the clustering.\n\n::: aside\nSee [Norms](./05-Distances-Timeseries.html#norms) in\n[Distances and Timeseries](./05-Distances-Timeseries.html) for a refresher.\n:::\n\n---\n\nWe now have a <font color=\"blue\">formal</font> definition of a clustering.\n\nThis is not the only definition possible, but it is an intuitive and simple one.\n\nHow hard is it to solve this problem?\n\n* $k=1$ and $k=n$ are easy special cases. Why?\n* But, this problem is __NP-hard__ if the dimension of the data is at least 2.\n    * We don't expect that there is any exact, efficient algorithm in general.\n\n__Nonetheless,__ there is a simple algorithm that works quite well in practice!\n\n\n## Aside: $k$-means as NP-hard\n\nFor context, **NP-hard** is a term used in the study of\n[computational complexity](https://en.wikipedia.org/wiki/Computational_complexity_theory).\n\nProblems in [**P**](https://en.wikipedia.org/wiki/P_(complexity)) are those that\ncan be solved in polynomial time,  e.g. for $n$ items, the time to solve the problem is $O(n^2)$ or $O(n^3)$.\n\nProblems in [**NP**](https://en.wikipedia.org/wiki/NP_(complexity)) are those that\ncan be _verified_ in polynomial time but not necessarily _solved_ in polynomial time.\n\n[**NP-hard**](https://en.wikipedia.org/wiki/NP-hardness) problems are those that are at least as hard as the hardest problems in **NP**, not necessarily verifiable in polynomial time.\n\n[**NP-complete**](https://en.wikipedia.org/wiki/NP-complete) problems are those that are both NP-hard and in NP, e.g. hardest problems in NP and verifiable in polynomial time.\n\nYou can prove that the $k$-means problem is NP-hard by finding a reduction from a known NP-hard problem such as the [**Partition Problem**](https://en.wikipedia.org/wiki/Partition_problem).\n\n\n## The $k$-means Algorithm\n\n:::: {.columns }\n\n::: {.column width=\"40%\"}\n![](figs/L06-top-ten-algorithms-cover.png){width=300 fig-align=\"center\"}\n:::\n\n::: {.column width=\"60%\"}\n* There is a \"classic\" algorithm for this problem.\n* It was voted among the __top-10 algorithms__ in data mining!^[As determined at the 2006 IEEE International Conference on Data Mining]\n* It is such a good idea that it has been independently discovered multiple times.\n* It was first discovered by Lloyd in 1957, so it is often called Lloyd's algorithm.\n* It is called the \"$k$-means algorithm.\"\n* Not to be confused with the $k$-means problem of which this is a heuristic solution.\n:::\n\n::::\n\n::: aside\nThe other from the top 10 were SVM, Apriori, EM, PageRank, AdaBoost, kNN, Naive Bayes, and CART.\n:::\n\n::: {.content-hidden when-profile=\"web\"}\n## The $k$-means algorithm\n:::\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n    - These can be randomly chosen data points, or by some other method such as\n     [$k$-means++](https://en.wikipedia.org/wiki/K-means%2B%2B)\n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n    - Nearer to $c_j$ than to any other center.\n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n    - In other words, $c_j$ is the mean of the vectors in $C_j$.\n4. Repeat (i.e., go to Step 2) until convergence.\n    - Either the cluster centers change below a threshold, or inertia changes below a threshold or a maximum number of iterations is reached.\n\n---\n\nLet's see this in practice with well separated clusters and also look at the Within-Cluster Sum of Square (WCSS).\n\n::: {#74b5e406 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-3-output-1.png){width=950 height=566}\n:::\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-3-output-2.png){width=950 height=566}\n:::\n:::\n\n\n---\n\nLet's see this in practice with overlapping clusters and also look at the WCSS.\n\n::: {#cb2650de .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-4-output-1.png){width=950 height=566}\n:::\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-4-output-2.png){width=950 height=566}\n:::\n:::\n\n\n---\n\n## Limitations of $k$-means\n\nAs you can see, $k$-means can work very well.\n\nHowever, we don't have any guarantees on the performance of $k$-means.\n\nIn particular, there are various settings in which $k$-means can fail to do a good job.\n\n\n## Limitation: non-spherical clusters\n\nBecause each point is assigned to its closest center, the points in a cluster are implicitly assumed to be arranged in a sphere around the center.\n\n::: {#34f5c075 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![K-means clustering on a dataset with anisotropic clusters.](06-Clustering-I-kmeans_files/figure-revealjs/cell-5-output-1.png){width=950 height=470 fig-align='center'}\n:::\n:::\n\n\n## Limitation: anisotropic clusters\n\n::: {#4c4d1028 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![K-means clustering on a dataset with anisotropic gaussian clusters.](06-Clustering-I-kmeans_files/figure-revealjs/cell-6-output-1.png){width=792 height=431}\n:::\n:::\n\n\n## Limitation: unequal-sized clusters\n\nFor the same reason, $k$-means tends to try to balance the sizes of the clusters.\n\n::: {#4540948d .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![K-means clustering on a dataset with unequal-sized clusters.](06-Clustering-I-kmeans_files/figure-revealjs/cell-7-output-1.png){width=792 height=431}\n:::\n:::\n\n\n## Limitation: unequal variance clusters\n\n::: {#22e2d788 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display}\n![K-means clustering on a dataset with unequal variance clusters.](06-Clustering-I-kmeans_files/figure-revealjs/cell-8-output-1.png){width=792 height=431}\n:::\n:::\n\n\n## Limitation: sensitive to starting cluster centers\n\nIf the initial guess (Step 1) is a bad one, $k$-means may get \"stuck\" in a bad solution.\n    \n![](figs/L06-kmeans-bad-initialization.png){width=600 fig-align=\"center\"}\n\n\n## Limitation: sensitive to number of clusters\n\n::: {#9bffa581 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![K-means clustering on a dataset with incorrect number of clusters parameter.](06-Clustering-I-kmeans_files/figure-revealjs/cell-9-output-1.png){width=792 height=431}\n:::\n:::\n\n\n## Choosing a Good Initialization\n\n* How can we avoid the kind of bad initialization we just saw?\n* A good strategy is to pick points that are distant to each other.\n* This strategy is called [\"$k$-means++\"](https://en.wikipedia.org/wiki/K-means%2B%2B).  \n* It works very well in practice, and the `scikit-learn` implementation uses it by default.\n* We will explore it in more detail in the next lecture.\n\n## Choosing the right $k$\n\nGiven some $K$, the $k$-means algorithm \"learns\" the cluster centers.\n\n::: {.fragment}\nHow do we choose the right number of clusters, $K$?\n:::\n\n::: {.fragment}\nAs an aside:\n\n* This parameter ($K$) is the first example we have seen of a __hyperparameter__.\n* A hyperparameter is a parameter that must be set before the model parameters can be learned.\n:::\n\n::: {.fragment}\nOur basic strategy will be to:\n\n* Iterate through different $K$ and use some criterion to decide which $K$ is most appropriate.\n* We will discuss this more in the next lecture.\n:::\n\n## Feature Scales\n\nFinally, given the tendency of $k$-means to look for spherical clusters, we should consider the scales of the various features.\n\nIn fact, in general when constructing or selecting a distance metric, one needs to think carefully about the scale of the features being used.\n\n## Unscaled Features\n\nFor example, consider the case where we are clustering people based on their age, income, and gender.\n\nWe might use age in years, income in dollars, and assign gender to the values $\\{0, 1\\}$.\n\nThus, the following records:\n\n* Joe Smith, age 27, income USD 75,000, male\n* Eve Jones, age 45, income USD 42,000, female\n\nWould be encoded in feature space as:\n\n$$\n\\begin{bmatrix}27\\\\75000\\\\0\\end{bmatrix},\\begin{bmatrix}45\\\\42000\\\\1\\end{bmatrix} \n$$\n\n## Unscaled Features, Continued\n\nWhat would happen if we used Euclidean distance as our dissimilarity metric in this feature space?\n\n(This is what $k$-means uses.)\n\n:::: {.fragment}\nClearly, the influence of income would dominate the other two features.  For\nexample, a difference of gender is about as significant as a difference of one\ndollar of yearly income.\n\nWe are unlikely to expose gender-based differences if we cluster using this representation.\n\nThe most common way to handle this is __feature scaling.__\n::::\n\n## Feature Scaling\n\nThe basic idea is to rescale each feature separately, so that its range of values is about the same as all other features.\n\nFor example, one may choose to:\n    \n* shift each feature independently by subtracting the mean over all observed values.\n    * This means that each feature is now centered on zero.\n* Then rescale each feature so that the standard deviation overall observed values is 1.\n    * This means that the feature will have about the same range of values as all the others.\n\n# $k$-means Clustering Examples\n\n# Example 1: Customer Segmentation\n\n## Customer Segmentation\n\nAnother powerful application of $k$-means clustering is **customer segmentation** in e-commerce.\n\n::: {.incremental}\n* Businesses want to understand their customers to provide better service and targeted marketing\n* Group customers with similar behaviors and characteristics $\\rightarrow$ **personas**\n* This enables personalized marketing campaigns, product recommendations, and customer service strategies\n:::\n\n## E-commerce Customer Data\n\nLet's synthesize e-commerce data to segment customers based on their purchasing behavior.\n\nHigh-value, frequent buyers; Moderate buyers; Bargain hunters; Occasional buyers.\n\n| Segment | Percentage | Annual Spending | Average Order Value | Total Orders |\n|---------|------------|----------------|---------------------|--------------|\n| High-value | 20% | $120 \\pm 20$ | $15 \\pm 3$ | $450 \\pm 80$ |\n| Moderate | 40% | $60 \\pm 15$ | $8 \\pm 2$ | $250 \\pm 50$ |\n| Bargain | 25% | $25 \\pm 8$ | $12 \\pm 4$ | $150 \\pm 30$ |\n| Occasional | 15% | $15 \\pm 5$ | $3 \\pm 1$ | $300 \\pm 60$ |\n\n## E-commerce Customer Data\n\n::: {#152401ed .cell execution_count=9}\n\n::: {.cell-output .cell-output-stdout}\n```\nE-commerce Customer Data Head:\n   Annual_Spending  Avg_Order_Value  Total_Orders  Customer_ID\n0             0.27             1.67        325.07            1\n1            27.74             4.78        127.63            2\n2            43.86             6.75        262.73            3\n3           132.78             9.23        345.36            4\n4            83.19             9.52        277.84            5\n\n\nE-commerce Customer Data Summary    :\n       Annual_Spending  Avg_Order_Value  Total_Orders  Customer_ID\ncount          1000.00          1000.00       1000.00      1000.00\nmean             57.12             9.39        275.20       500.50\nstd              39.33             6.80        116.85       288.82\nmin              -8.21           -10.90         63.74         1.00\n25%              23.26             4.87        178.72       250.75\n50%              50.96             9.26        257.75       500.50\n75%              78.22            13.76        337.32       750.25\nmax             166.33            35.01        760.47      1000.00\n```\n:::\n:::\n\n\n## Understanding Customer Features\n\n::: {#c810e2fa .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Distribution of customer features](06-Clustering-I-kmeans_files/figure-revealjs/cell-11-output-1.png){width=1430 height=470}\n:::\n:::\n\n\n> Can you see clusters?\n\n## Feature Scaling is Critical\n\nBefore clustering, we need to scale our features since they have very different ranges:\n\n::: {#a87e9fd0 .cell execution_count=11}\n\n::: {.cell-output .cell-output-stdout}\n```\nOriginal feature ranges:\nAnnual Spending: $-8 - $166\nAvg Order Value: $-11 - $35\nTotal Orders: 64 - 760\n\nScaled feature ranges:\nAnnual Spending: -1.66 - 2.78\nAvg Order Value: -2.99 - 3.77\nTotal Orders: -1.81 - 4.16\n```\n:::\n:::\n\n\n## Searching Cluster Numbers\n\nWhat cluster number should we pick?\n\n::: {#0d6e01b4 .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Elbow method for determining optimal number of clusters](06-Clustering-I-kmeans_files/figure-revealjs/cell-13-output-1.png){width=950 height=566}\n:::\n:::\n\n\n## Customer Segmentation Results\n\nVisualize in 2D using PCA which we'll cover later.\n\n::: {#f68fa3e5 .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![K-means customer segmentation results](06-Clustering-I-kmeans_files/figure-revealjs/cell-14-output-1.png){width=1142 height=470}\n:::\n:::\n\n\n## Customer Segment Profiles\n\n::: {#f9ffeae3 .cell execution_count=14}\n\n::: {.cell-output .cell-output-stdout}\n```\nCustomer Segment Profiles:\n============================================================\n\nSegment 0 (193 customers):\n  • Average Annual Spending: $121\n  • Average Order Value: $15\n  • Average Total Orders: 458.9\n\nSegment 1 (251 customers):\n  • Average Annual Spending: $28\n  • Average Order Value: $14\n  • Average Total Orders: 161.1\n\nSegment 2 (255 customers):\n  • Average Annual Spending: $26\n  • Average Order Value: $2\n  • Average Total Orders: 268.5\n\nSegment 3 (301 customers):\n  • Average Annual Spending: $67\n  • Average Order Value: $8\n  • Average Total Orders: 258.3\n```\n:::\n:::\n\n\n| Segment | Percentage | Annual Spending | Average Order Value | Total Orders |\n|---------|------------|----------------|---------------------|--------------|\n| High-value | 20% | $120 \\pm 20$ | $15 \\pm 3$ | $450 \\pm 80$ |\n| Moderate | 40% | $60 \\pm 15$ | $8 \\pm 2$ | $250 \\pm 50$ |\n| Bargain | 25% | $25 \\pm 8$ | $12 \\pm 4$ | $150 \\pm 30$ |\n| Occasional | 15% | $15 \\pm 5$ | $3 \\pm 1$ | $300 \\pm 60$ |\n\n\n# Example 2: Plant Classification Based on Morphology\n\n## Plant Species Classification with Iris Data\n\nLet's explore another real-world application using the famous **Iris dataset** from scikit-learn.\n\n::: {.incremental}\n* The Iris dataset contains measurements of 150 iris flowers from 3 species\n* Each flower has 4 features: sepal length, sepal width, petal length, and petal width\n* This is a classic example where we know the true species but want to see if k-means can discover these natural groupings\n:::\n\n## Loading and Exploring the Iris Dataset\n\n::: {#55069a11 .cell execution_count=15}\n\n::: {.cell-output .cell-output-stdout}\n```\nIris Dataset Information:\n========================================\nNumber of samples: 150\nNumber of features: 4\nFeature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']\nTarget names: ['setosa' 'versicolor' 'virginica']\nNumber of species: 3\n\nFirst 5 samples:\nSepal Length Sepal Width Petal Length Petal Width Species \n------------------------------------------------------------\n5.1          3.5         1.4          0.2         setosa  \n4.9          3.0         1.4          0.2         setosa  \n4.7          3.2         1.3          0.2         setosa  \n4.6          3.1         1.5          0.2         setosa  \n5.0          3.6         1.4          0.2         setosa  \n```\n:::\n:::\n\n\n## Visualizing Iris Data in 2D\n\nLet's compare features in pairs. Do you see clusters?\n\n::: {#e5c514e2 .cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-17-output-1.png){width=758 height=566}\n:::\n:::\n\n\n## Visualizing Iris Data in 2D\n\nFeature pairs with ground truth labels.\n\n::: {#06e95641 .cell execution_count=17}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-18-output-1.png){width=758 height=566}\n:::\n:::\n\n\n> Question: What observations can you make?\n\n\n## Try different cluster numbers\n\n::: {#dd462eae .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-19-output-1.png){width=950 height=566}\n:::\n:::\n\n\n## K-means Clustering on Iris Data\n\nResults for $k=3$ clusters.\n\n::: {#95cf7ece .cell execution_count=19}\n\n::: {.cell-output .cell-output-stdout}\n```\n\nConfusion Matrix:\nRows: True species, Columns: Predicted clusters\n            Cluster 0  Cluster 1  Cluster 2\nsetosa              0         50          0\nversicolor         48          0          2\nvirginica          14          0         36\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-20-output-2.png){width=1430 height=566}\n:::\n:::\n\n\n## Analysis\n\n::: {#14dd4e6f .cell execution_count=20}\n\n::: {.cell-output .cell-output-stdout}\n```\nCluster Analysis:\n==================================================\n\nCluster 0:\n  • Size: 62 samples\n  • Dominant species: versicolor (77.4%)\n  • Average petal length: 4.4 cm\n  • Average petal width: 1.4 cm\n  • Average sepal length: 5.9 cm\n  • Average sepal width: 2.7 cm\n\nCluster 1:\n  • Size: 50 samples\n  • Dominant species: setosa (100.0%)\n  • Average petal length: 1.5 cm\n  • Average petal width: 0.2 cm\n  • Average sepal length: 5.0 cm\n  • Average sepal width: 3.4 cm\n\nCluster 2:\n  • Size: 38 samples\n  • Dominant species: virginica (94.7%)\n  • Average petal length: 5.7 cm\n  • Average petal width: 2.1 cm\n  • Average sepal length: 6.9 cm\n  • Average sepal width: 3.1 cm\n```\n:::\n:::\n\n\n## Key Insights:\n\n* K-means successfully identified the three iris species\n* Setosa is perfectly separated from the other species\n* Versicolor and Virginica show some overlap, which is realistic\n* Petal measurements are more discriminative than sepal measurements\n* Overall clustering quality pretty good!\n\n\n## Why K-means Works Well on Iris Data\n\n* **Well-separated clusters**: The three iris species have distinct characteristics\n* **Spherical cluster shapes**: Each species forms roughly spherical groups in feature space\n* **Appropriate feature scaling**: All measurements are in the same units (centimeters)\n* **A Priori knowledge**: We know the true number of species (cluster number)\n\n# Example 3: k-means image compression\n\n## k-means image compression\n\nHere is a simple example of how $k$-means can be used to reduce\ncolor space and compress data.\n\nConsider the following image.  \n\n* Each color in the image is represented by an integer.  \n* Typically we might use 24 bits for each integer (8 bits for R, G, and B).\n    \n![](figs/L6-annie19980405.jpg){width=350 fig-align=\"center\"}\n\n::: {.content-hidden when-profile=\"web\"}\n## Example, Continued\n:::\n\nNow find $k=16$ clusters of pixels in three dimensional $(R, G, B)$ space\nand replace each pixel by its cluster center.\n\nBecause there are 16 centroids, we can represent by a 4-bit mapping \nfor a compression ratio of $24/4=6\\times$.\n    \n![](figs/L6-annie_016.png){width=500 fig-align=\"center\"}\n\n::: {.content-hidden when-profile=\"web\"}\n## Example, Continued\n:::\n\nHere we cluster into 8 groups (3 bits) for a compression ratio $24/3=8\\times$.\n    \n![](figs/L6-annie_008.png){width=500 fig-align=\"center\"}\n\n::: {.content-hidden when-profile=\"web\"}\n## Example, Continued\n:::\n\nHere we cluster into 4 groups (2 bits) for a compression ratio around $24/2=12\\times$.\n    \n![](figs/L6-annie_004.png){width=500 fig-align=\"center\"}\n\n::: {.content-hidden when-profile=\"web\"}\n## Example, Continued\n:::\n\nFinally, we use 1 bit (2 color groups) for a compression ratio of $24\\times$.\n    \n![](figs/L6-annie_002.png){width=500 fig-align=\"center\"}\n\n\n# In-Class Activity: k-Means Clustering\n\n**Time: 10 minutes**  \n**Materials: Pencil and paper**  \n**Objective: Understand the k-means algorithm through 1D visualization**\n\n\n\n## Activity: \"Clustering 1D Data\"\n\n### The Data\n\nWe have 8 data points on a number line that form 2 natural clusters:\n\n**Data Points**: 1.2, 1.8, 2.1, 7.3, 7.9, 8.2, 9.1, 10.5\n\n::: {#427d4abe .cell execution_count=22}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-23-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n:::\n\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## The Steps\n\n1. **Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.**\n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## Step 1: Cluster Centers Initialization\n\n**Assume our randomly chosen initial centers are**:\n\n- Center A = 4.0, Center B = 11.0\n\n::: {#7307ebaa .cell execution_count=23}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-24-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n:::\n\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. **For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.**\n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## Step 2: Assignment (2 minutes)\n\nFor each data point, calculate the distance to both centers and assign it to the closer one.\n\n**Complete the table**:\n\n| Point | Value | Distance to A (4.0) | Distance to B (11.0) | Assigned to |\n|-------|-------|---------------|---------------|-------------|\n| 1     | 1.2   | 2.8           | 9.8           | A           |\n| 2     | 1.8   |              |              |            |\n| 3     | 2.1   |              |              |            |\n| 4     | 7.3   |              |              |            |\n| 5     | 7.9   |              |              |            |\n| 6     | 8.2   |              |              |            |\n| 7     | 9.1   |              |              |            |\n| 8     | 10.5  |              |              |            |\n\n## Assignment Visualization\n\n::: {#4855e7f9 .cell execution_count=24}\n\n::: {.cell-output .cell-output-display}\n![Assignment visualization with cluster colors](06-Clustering-I-kmeans_files/figure-revealjs/cell-25-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n:::\n\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n3. **For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.**  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## Step 3: Update Centers (2 minutes)\n\nCalculate the new centers based on the assigned points.\n\n**Cluster A** (points: 1.2, 1.8, 2.1, 7.3):\n\n- New center A = \n\n**Cluster B** (points: 7.9, 8.2, 9.1, 10.5):\n\n- New center B = \n\n## Step 3: Update Centers\n\nCalculate the new centers based on the assigned points.\n\n**Cluster A** (points: 1.2, 1.8, 2.1, 7.3):\n\n- New center A = (1.2 + 1.8 + 2.1 + 7.3) ÷ 4 = 3.1\n\n**Cluster B** (points: 7.9, 8.2, 9.1, 10.5):\n\n- New center B = (7.9 + 8.2 + 9.1 + 10.5) ÷ 4 = 8.9\n\n## Step 3: Update Centers Visualization\n\n::: {#9305331f .cell execution_count=25}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-26-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNew Center A: 3.1\nNew Center B: 8.9\n```\n:::\n:::\n\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n4. **Repeat (i.e., go to Step 2) until convergence.**\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. **For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.**  \n3. For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## Step 4: Second Iteration Cluster Assignment (2 minutes)\n\nRepeat the assignment with the new centers ($A' = 3.1, B' = 8.9$).\n\n**Complete the table**:\n\n| Point | Value | Distance to $A'$ | Distance to $B'$ | Assigned to |\n|-------|-------|----------------|----------------|-------------|\n| 1     | 1.2   | 1.9            | 8.3            | A           |\n| 2     | 1.8   |               |               |            |\n| 3     | 2.1   |               |               |            |\n| 4     | 7.3   |               |               |            |\n| 5     | 7.9   |               |               |            |\n| 6     | 8.2   |               |               |            |\n| 7     | 9.1   |               |               |            |\n| 8     | 10.5  |               |               |            |\n\n## Step 4: Second Iteration Cluster Assignment Visualization\n\n::: {#8e0959c8 .cell execution_count=26}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-27-output-1.png){width=1142 height=373 fig-align='center'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNew Center A: 3.1\nNew Center B: 8.9\n```\n:::\n:::\n\n\n## Convergence Check\n\nOne type of convergence is when the centers stop changing.\n\n| 1st Iteration Center | 2nd Iteration Center | Abs Difference |\n|----------------------|----------------------|----------------|\n| A = 4               | A = 3.1                | 0.9            |\n| B = 11              | B = 8.9                | 2.1            |\n\nShould we do another iteration?\n\n## The Steps\n\n1. Pick $K$ cluster centers $\\{c_1, \\dots, c_K\\}$.  \n2. For each $j$, define the cluster $C_j$ as the set of points in $X$ that are <font color=\"blue\">closest to center</font> $c_j$.  \n3. **For each $j$, update $c_j$ to be <font color=\"blue\">the center of mass of cluster</font> $C_j$.**  \n4. Repeat (i.e., go to Step 2) until convergence.\n\n## 2nd Iteration Update Centers\n\n**Cluster A** (points: 1.2, 1.8, 2.1):\n\n- New center A = (1.2 + 1.8 + 2.1) ÷ 3 = 1.7\n\n**Cluster B** (points: 7.3, 7.9, 8.2, 9.1, 10.5):\n\n- New center B = (7.3 + 7.9 + 8.2 + 9.1 + 10.5) ÷ 5 = 8.6\n\n## Step 4: Second Iteration Visualization\n\n::: {#def62036 .cell execution_count=27}\n\n::: {.cell-output .cell-output-display}\n![](06-Clustering-I-kmeans_files/figure-revealjs/cell-28-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n:::\n\n\n## Step 5: Check for Convergence (1 minute)\n\n**Questions**:\n\n- Would cluster assignments change if we continued?\n- Would the centers change if we continued?\n- Have we found the optimal clustering?\n\n\n## Key Learning Points\n\n1. **Algorithm Steps**: Initialize → Assign → Update → Repeat\n2. **Distance Calculation**: |point - center| in 1D\n3. **Center Updates**: Average of assigned points\n4. **Convergence**: Centers stop changing when optimal\n5. **Initialization Matters**: Different starts can lead to different results\n\n## Quick Assessment\n\n**Answer on your paper**:\n\n1. **What is the correct order of the 4 steps of k-means?**\n   - [ ] Repeat until convergence\n   - [ ] Assign points to closest center\n   - [ ] Initialize centers\n   - [ ] Update centers to average of assigned points\n\n2. **How do you update a center?**\n   - Answer: \n\n3. **What does \"convergence\" mean?**\n   - Answer: \n\n\n## Recap and Next\n\nToday we covered:\n\n* $k$-means clustering\n* strengths and weaknesses\n* Importance of initialization and cluster number\n* Feature scaling\n* Example applications:\n  * Customer segmentation\n  * Plant species classification with Iris data\n  * Image color compression\n\nComing up next, we'll look at some practical aspects of applying $k$-means.\n\n",
    "supporting": [
      "06-Clustering-I-kmeans_files"
    ],
    "filters": [],
    "includes": {}
  }
}