{
  "hash": "a8fa15631655bc4719ee55a6ce06e386",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Time Series Analysis'\njupyter: python3\nbibliography: references.bib\n---\n\n## Colab\n\n[![](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/tools4ds/DS701-Course-Notes/blob/main/ds701_book/jupyter_notebooks/26-TimeSeries.ipynb)\n\n\n# Introduction to Time Series\n\n## What is a Time Series?\n\n::: {#04454a84 .cell execution_count=1}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-2-output-1.png){width=816 height=302 fig-align='center'}\n:::\n:::\n\n\n**Time series** = data points indexed by time (hourly, daily, monthly...)\n\nTwo key goals:\n\n1. **Analysis**: What patterns exist? Trends? Seasonality? Anomalies?\n2. **Forecasting**: What comes next?\n\n## Time Series Are Everywhere\n\n::: {#3854f119 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-3-output-1.png){width=819 height=302 fig-align='center'}\n:::\n:::\n\n\n| Domain | Example Questions |\n|--------|-------------------|\n| **Finance** | Will this stock go up? What's my portfolio risk? |\n| **Healthcare** | Is this patient's vitals trending abnormally? |\n| **Climate** | How much warmer will next decade be? |\n| **Retail** | How much inventory do I need for Black Friday? |\n\n## The Four Components\n\nEvery time series can be decomposed into:\n\n| Component | What it captures | Example |\n|-----------|------------------|---------|\n| **Trend** | Long-term direction | \"Are EV sales growing?\" |\n| **Seasonality** | Fixed-period cycles | \"Ice cream sales spike in summer\" |\n| **Cyclic** | Variable-length oscillations | \"Business cycles\" |\n| **Noise** | Random variation | \"Day-to-day fluctuations\" |\n\n## Today's Roadmap\n\n1. **Visualize** — See patterns before modeling\n2. **Decompose** — Separate trend, seasonality, noise\n3. **Test** — Is it stationary? (Spoiler: it matters)\n4. **Model** — AR, MA, ARIMA, SARIMA\n5. **Forecast** — Predict the future (with uncertainty)\n\n::: {.content-visible when-profile=\"slides\"}\n## Time and Date in Python\n\n> See course notes for datetime/pandas manipulation details \n> (based on [Python for Data Analysis, 3rd Ed.](https://wesmckinney.com/book/time-series))\n:::\n\n::: {.content-visible when-profile=\"web\"}\n# Time and Date Manipulation\n\nMany time series data sets are indexed by date or time. The python `datetime`\nlibrary and the `pandas` library provide a powerful set of tools for manipulating\ntime series data.\n\nThe [Time Series](https://wesmckinney.com/book/time-series) chapter of the book\n[Python for Data Analysis, 3rd Ed.](https://wesmckinney.com/book/time-series)\nprovides a good overview of these tools. We'll share a few excerpts here.\n\n::: {#e1066fab .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\nDate and time when this cell was executed: 2026-07-30 17:08:18.336216\nYear: 2026, month: 7, day: 30\nSince beginning of 2024 till when this cell was run there were 941 days and 61698 seconds.\n```\n:::\n:::\n\n\nYou can also convert between strings and datetime.\n\n::: {#1ee503ac .cell execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\n2024-01-01 00:00:00\n```\n:::\n:::\n\n\nYou can also format datetime objects as strings.\n\n::: {#1a0398ab .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n2026-07-30\n```\n:::\n:::\n\n\nSee Table 11.2 in the [book](https://wesmckinney.com/book/time-series) for a list of formatting codes.\n\nLet's explore some of the pandas time series tools.\n\nCreate a time series with a datetime index.\n\n::: {#de3ceea7 .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\n<class 'pandas.core.series.Series'>\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n2022-01-01   -2.356871\n2022-01-02    1.027206\n2022-01-03   -0.446585\n2022-01-04    0.800750\n2022-01-05    0.202357\n                ...   \n2024-09-22    0.349732\n2024-09-23    0.475475\n2024-09-24   -1.224398\n2024-09-25   -0.610577\n2024-09-26    0.289065\nFreq: D, Length: 1000, dtype: float64\n```\n:::\n:::\n\n\nWe can access just the samples from 2023 with simply:\n\n::: {#f413a282 .cell execution_count=7}\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n2023-01-01   -0.884336\n2023-01-02   -1.481391\n2023-01-03   -0.923543\n2023-01-04   -0.279017\n2023-01-05    2.533902\n                ...   \n2023-12-27   -0.026741\n2023-12-28    1.938192\n2023-12-29    1.740794\n2023-12-30   -0.839916\n2023-12-31   -1.159051\nFreq: D, Length: 365, dtype: float64\n```\n:::\n:::\n\n\nOr the month of September 2023:\n\n::: {#9c9323e4 .cell execution_count=8}\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n2023-09-01    0.170552\n2023-09-02   -0.665221\n2023-09-03   -2.132044\n2023-09-04    0.428844\n2023-09-05    0.900554\n2023-09-06    0.915570\n2023-09-07    0.472974\n2023-09-08    1.741738\n2023-09-09    1.211779\n2023-09-10    1.133827\n2023-09-11    1.066044\n2023-09-12    0.333499\n2023-09-13   -0.836529\n2023-09-14   -1.096511\n2023-09-15    0.392706\n2023-09-16    0.577394\n2023-09-17   -0.463646\n2023-09-18   -0.086288\n2023-09-19    0.925784\n2023-09-20   -0.692628\n2023-09-21    0.580879\n2023-09-22   -0.719557\n2023-09-23   -1.244265\n2023-09-24   -3.324379\n2023-09-25   -1.026125\n2023-09-26    0.462286\n2023-09-27   -2.088208\n2023-09-28    0.583594\n2023-09-29    0.619105\n2023-09-30   -0.412775\nFreq: D, dtype: float64\n```\n:::\n:::\n\n\nOr slice by date range:\n\n::: {#487f49b6 .cell execution_count=9}\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n2023-03-01    1.658701\n2023-03-02   -2.129902\n2023-03-03    1.554606\n2023-03-04   -0.546281\n2023-03-05   -0.252550\n2023-03-06    1.648764\n2023-03-07   -0.573878\n2023-03-08   -0.557951\n2023-03-09   -0.691837\n2023-03-10   -0.573799\nFreq: D, dtype: float64\n```\n:::\n:::\n\n\nor:\n\n::: {#8110284b .cell execution_count=10}\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\n2023-09-15    0.392706\n2023-09-16    0.577394\n2023-09-17   -0.463646\n2023-09-18   -0.086288\n2023-09-19    0.925784\n                ...   \n2024-09-22    0.349732\n2024-09-23    0.475475\n2024-09-24   -1.224398\n2024-09-25   -0.610577\n2024-09-26    0.289065\nFreq: D, Length: 378, dtype: float64\n```\n:::\n:::\n\n\nThere are many more time series tools available that let you do things like:\n\n- Shifting and setting frequencies of date ranges\n- Time zone handling\n- Time series resampling\n- Time series rolling and expanding windows\n\n## Moving Window Functions\n\nLet's dive into the moving window functions.\n\n::: {#181f2833 .cell execution_count=11}\n\n::: {.cell-output .cell-output-stdout}\n```\n                Close       High        Low       Open     Volume\nDate                                                             \n2012-01-05  12.513906  12.529472  12.353452  12.421706  271269600\n2012-01-06  12.644725  12.655202  12.549530  12.565995  318292800\n2012-01-09  12.624668  12.804880  12.613292  12.737525  394024400\n2012-01-10  12.669870  12.752492  12.617782  12.749798  258196400\n2012-01-11  12.649214  12.658195  12.552223  12.653105  215084800\n```\n:::\n:::\n\n\n::: {#f2f991f4 .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-13-output-1.png){width=798 height=401}\n:::\n:::\n\n\n:::\n\n# Visualization\n\nAlways visualize first! Let's explore patterns in a classic dataset.\n\n## Air Passengers Dataset\n\n\n\nWe're going to use a dataset of air passengers per month from 1949 to 1960.\n\n::: {#087da5ff .cell execution_count=14}\n\n::: {.cell-output .cell-output-display execution_count=14}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Number of Passengers</th>\n    </tr>\n    <tr>\n      <th>Date</th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1949-01-01</th>\n      <td>112</td>\n    </tr>\n    <tr>\n      <th>1949-02-01</th>\n      <td>118</td>\n    </tr>\n    <tr>\n      <th>1949-03-01</th>\n      <td>132</td>\n    </tr>\n    <tr>\n      <th>1949-04-01</th>\n      <td>129</td>\n    </tr>\n    <tr>\n      <th>1949-05-01</th>\n      <td>121</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n## Time Series Plot\n\nLet's look at the time series plot.\n\n::: {#80fe184d .cell execution_count=15}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-16-output-1.png){width=816 height=376 fig-align='center'}\n:::\n:::\n\n\nClearly there are some trends and seasonality in the data.\n\nClearly: **trend** (going up) + **seasonality** (annual pattern) + **growing amplitude**.\n\n---\n\nLet's visualize that seasonal pattern more explicitly:\n\n::: {#b1076f93 .cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-17-output-1.png){width=816 height=429 fig-align='center'}\n:::\n:::\n\n\nNotice: the seasonal amplitude is **growing** over time — important for model choice!\n\n---\n\nLet's look at the distribution across years and months:\n\n::: {#05ca986d .cell execution_count=17}\n``` {.python .cell-code}\n# Add normalized column for later use\nimport matplotlib.pyplot as plt\nair_passengers['Normalized_Passengers'] = air_passengers.groupby('Year')['Number of Passengers'].transform(lambda x: x / x.iloc[0])\n\n# Create side-by-side plots\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))\n\n# Year-wise box plot\nsns.boxplot(data=air_passengers, x='Year', y='Number of Passengers', palette='tab10', ax=ax1)\nax1.set_title('By Year: Clear Upward Trend')\nax1.set_ylabel('Passengers')\nax1.tick_params(axis='x', rotation=45)\n\n# Month-wise box plot  \nsns.boxplot(data=air_passengers, x='Month', y='Number of Passengers', palette='tab10', hue='Month', legend=False, ax=ax2)\nax2.set_title('By Month: Summer Peak (Jul-Aug)')\nax2.set_ylabel('Passengers')\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-18-output-1.png){width=1142 height=374 fig-align='center'}\n:::\n:::\n\n\n**Left**: Trend is obvious. **Right**: July-August are peak travel months.\n\n> Box plot: median, Q1-Q3 Interquartile Range, Whiskers: $1.5\\times \\text{IQR}$\n\n## Autocorrelation: The Key Diagnostic\n\n**Autocorrelation** = correlation between $y_t$ and $y_{t-k}$ (lagged by $k$ steps)\n\n$$\n\\rho_k = \\frac{\\sum_{t=k+1}^{T} (y_t - \\bar{y})(y_{t-k} - \\bar{y})}{\\sum_{t=1}^{T} (y_t - \\bar{y})^2}\n$$\n\n**Why it matters:**\n\n- High autocorrelation (for $k>0$) → values depend on past → predictable!\n- Peaks at regular lags → seasonality\n- No autocorrelation → white noise (unpredictable)\n\n## ACF of Air Passengers\n\n::: {#bb798f66 .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-19-output-1.png){width=813 height=431 fig-align='center'}\n:::\n:::\n\n\n**Reading the ACF**: Blue shading = 95% CI. Peak at lag 12 is significant → yearly seasonality confirmed!\n\n# Time Series Decomposition\n\n## The Goal: Separate Signal from Noise\n\nWe want to break apart: **Observed = Trend + Seasonality + Residual**\n\nWhy?\n\n- **Understand** the underlying patterns\n- **Remove** seasonality for cleaner modeling  \n- **Detect** anomalies in the residuals\n- **Forecast** each component separately\n\n## Additive vs Multiplicative\n\n**How do the components combine?**\n\n| Model | Formula | When to use |\n|-------|---------|-------------|\n| **Additive** | $Y = T + S + \\epsilon$ | Seasonal amplitude is constant |\n| **Multiplicative** | $Y = T \\times S \\times \\epsilon$ | Seasonal amplitude grows with trend |\n\nLook back at air passengers: amplitude **grows** → multiplicative is better!\n\n## Classical Decomposition: The Algorithm\n\n**Steps:**\n\n1. **Estimate trend** — moving average smooths out seasonality\n2. **Remove trend** — detrended = observed - trend  \n3. **Estimate seasonality** — average each month's detrended values\n4. **Residual** — what's left after removing trend & seasonality\n\n---\n\nLet's do it step by step:\n\n::: {#093ea2ac .cell execution_count=19}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-20-output-1.png){width=950 height=758 fig-align='center'}\n:::\n:::\n\n\n**Question**: Is the residual truly random? (Hint: look at the variance over time)\n\n\n## STL: A Better Decomposition\n\n**STL** = Seasonal-Trend decomposition using Loess [@cleveland1990stl]\n\nWhy STL over classical?\n\n- ✅ Handles **changing seasonality** (amplitude can vary)\n- ✅ Robust to **outliers**\n- ✅ Works with **any period** (not just 12 months)\n\n> See course notes for details on Loess (locally weighted regression)\n\n::: {.content-visible when-profile=\"web\"}\n\n## Locally Estimated Scatterplot Smoothing -- Loess[^gpt4o]\n\n[^gpt4o]: gpt-4o, personal communication, Nov 2024\n\n**Loess**, which stands for \"Locally Estimated Scatterplot Smoothing,\" is a non-parametric method used to estimate non-linear relationships in data. It is particularly useful for smoothing scatterplots and is a type of local regression.\n\n### Key Features of Loess:\n\n1. **Local Fitting**: Loess fits simple models to localized subsets of the data to build up a function that describes the deterministic part of the variation in the data, point by point.\n\n2. **Weighted Least Squares**: It uses weighted least squares to fit a polynomial surface to the data. The weights decrease with distance from the point of interest, giving more influence to points near the target point.\n\n3. **Flexibility**: Loess is flexible and can model complex relationships without assuming a specific global form for the data. It can adapt to various shapes and patterns in the data.\n\n4. **Smoothing Parameter**: The degree of smoothing is controlled by a parameter, often denoted as $\\alpha$ or the span. This parameter determines the proportion of data points used in each local fit. A smaller span results in a curve that follows the data more closely, while a larger span results in a smoother curve.\n\n5. **Polynomial Degree**: Loess can fit either linear or quadratic polynomials to the data. The choice of polynomial degree affects the smoothness and flexibility of the fit.\n\n### How Loess Works:\n\n- **Step 1**: For each point in the dataset, a neighborhood of points is selected based on the smoothing parameter.\n- **Step 2**: A weighted least squares regression is performed on the points in the neighborhood, with weights decreasing with distance from the target point.\n- **Step 3**: The fitted value at the target point is computed from the local regression model.\n- **Step 4**: This process is repeated for each point in the dataset, resulting in a smooth curve that captures the underlying trend.\n\n### Applications:\n\nLoess is widely used in exploratory data analysis to visualize trends and patterns in data. It is particularly useful when the relationship between variables is complex and not well-represented by a simple linear or polynomial model.\n\n### Example in Python:\n\nIn Python, the `statsmodels` library provides a function for performing Loess smoothing:\n\n::: {#14f890d1 .cell execution_count=20}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-21-output-1.png){width=805 height=411}\n:::\n:::\n\n\nIn this example, `frac` is the smoothing parameter that controls the amount of smoothing applied to the data.\n:::\n\n## In Practice: `statsmodels`\n\n\n\n## Additive vs Multiplicative: See the Difference\n\n::: {#1f713441 .cell execution_count=22}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-23-output-1.png){width=1334 height=566 fig-align='center'}\n:::\n:::\n\n\n**Key insight**: Multiplicative residuals are more uniform — better fit!\n\n## STL in Action\n\n::: {#89a93b0e .cell execution_count=23}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-24-output-1.png){width=950 height=566 fig-align='center'}\n:::\n:::\n\n\n# Stationarity: Why It Matters\n\n## The Stationarity Problem\n\n**Stationary** = statistical properties (mean, variance) don't change over time\n\n**Why do we care?**\n\nMost forecasting models **assume stationarity**. \n\nIf your data has:\n\n- 📈 Trend → mean is changing\n- 📊 Growing variance → variance is changing  \n- 🔄 Seasonality → periodic non-stationarity\n\n...the model will fail. We must **transform** the data first.\n\n## Making Data Stationary\n\n| Problem | Solution |\n|---------|----------|\n| Trend | **Differencing**: $y'_t = y_t - y_{t-1}$ |\n| Growing variance | **Log transform**: $y'_t = \\log(y_t)$ |\n| Seasonality | **Seasonal differencing**: $y'_t = y_t - y_{t-12}$ |\n\n## Testing for Stationarity\n\nTwo standard tests (both in `statsmodels`):\n\n| Test | Null Hypothesis | Reject means... |\n|------|-----------------|-----------------|\n| **ADF** | Has unit root (non-stationary) | Stationary ✓ |\n| **KPSS** | Is stationary | Non-stationary ✗ |\n\n**ADF (Augmented Dickey-Fuller)**: Tests whether a \"unit root\" is present — a mathematical property that causes non-stationarity. The test includes lagged differences to handle autocorrelation. If p-value < 0.05, reject the null → evidence the series is **stationary**.\n\n**KPSS (Kwiatkowski-Phillips-Schmidt-Shin)**: Flips the hypothesis — assumes stationarity and tests for evidence against it. Checks stats on residuals of the trend-stationary series. If p-value < 0.05, reject the null → evidence the series is **non-stationary**.\n\n## Stationarity Tests Continued\n\n**Why use both?** They have opposite null hypotheses, so using them together provides stronger evidence:\n\n| ADF Result | KPSS Result | Conclusion |\n|------------|-------------|------------|\n| Reject (p<0.05) | Fail to reject | Stationary ✓ |\n| Fail to reject | Reject (p<0.05) | Non-stationary ✗ |\n| Both reject | Both reject | Trend-stationary (difference needed) |\n| Neither rejects | Neither rejects | Inconclusive — gather more data |\n\n> See course notes for worked examples of ADF and KPSS tests\n\n::: {.content-visible when-profile=\"web\"}\n\n## ADF Test Demonstration\n\nLet's apply the tests, starting with ADF:\n\n::: {#5638c3c0 .cell execution_count=24}\n\n::: {.cell-output .cell-output-stdout}\n```\nADF Statistic: 0.8153688792060514\np-value: 0.991880243437641\nCritical Values:\n\t1%: -3.482\n\t5%: -2.884\n\t10%: -2.579\n```\n:::\n:::\n\n\n### Interpretation:\n\n1. **ADF Statistic**: The ADF statistic is 0.815, which is greater than all the critical values at the 1%, 5%, and 10% significance levels.\n\n2. **p-value**: The p-value is 0.991, which is significantly higher than common significance levels (e.g., 0.01, 0.05, 0.10).\n\n3. **Critical Values**:\n   - 1%: -3.482\n   - 5%: -2.884\n   - 10%: -2.579\n\n### Conclusion:\n\n- **Fail to Reject the Null Hypothesis**: Since the ADF statistic (0.815) is greater than the critical values and the p-value (0.991) is much higher than typical significance levels, you fail to reject the null hypothesis. This suggests that the time series has a unit root and is non-stationary.\n\n- **Implication**: The time series data for the number of passengers is non-stationary, indicating that it may have a trend or other non-stationary components. To make the series stationary, you might consider differencing the data or applying other transformations, such as detrending or seasonal adjustment, before proceeding with further analysis or modeling.\n\n## KPSS Test Demonstration\n\nLet's apply the KPSS test.\n\n::: {#0df317ef .cell execution_count=25}\n\n::: {.cell-output .cell-output-stdout}\n```\n\nKPSS Statistic: 1.6513122354165206\np-value: 0.01\nCritical Values:\n\t10%: 0.347\n\t5%: 0.463\n\t2.5%: 0.574\n\t1%: 0.739\n```\n:::\n:::\n\n\nThe KPSS (Kwiatkowski-Phillips-Schmidt-Shin) test is another test used to assess the stationarity of a time series, but it has a different null hypothesis compared to the ADF test.\n\n### KPSS Test Interpretation:\n\n1. **Null Hypothesis (\\(H_0\\))**: The null hypothesis of the KPSS test is that the time series is stationary around a deterministic trend (i.e., it does not have a unit root).\n\n2. **Alternative Hypothesis (\\(H_1\\))**: The alternative hypothesis is that the time series is not stationary (i.e., it has a unit root).\n\n### Given Results:\n\n- **KPSS Statistic**: 1.651\n- **p-value**: 0.01\n- **Critical Values**:\n  - 10%: 0.347\n  - 5%: 0.463\n  - 2.5%: 0.574\n  - 1%: 0.739\n\n### Conclusion:\n\n- **Reject the Null Hypothesis**: The KPSS statistic (1.651) is greater than all the critical values at the 10%, 5%, 2.5%, and 1% significance levels. This, along with the low p-value (0.01), suggests that you reject the null hypothesis of stationarity.\n\n- **Implication**: The time series is likely non-stationary according to the KPSS test. This aligns with the ADF test results, which also indicated non-stationarity.\n\n### Overall Interpretation:\n\nBoth the ADF and KPSS tests suggest that the time series is non-stationary. This consistent result from both tests strengthens the conclusion that the series may need differencing or other transformations to achieve stationarity before further analysis or modeling.\n\n:::\n\n# Time Series Models\n\n## The ARIMA Family\n\nBuilding blocks for forecasting:\n\n| Model | Idea | Parameters |\n|-------|------|------------|\n| **AR(p)** | Past **values** predict future | $y_t = c + \\phi_1 y_{t-1} + ... + \\epsilon_t$ |\n| **MA(q)** | Past **errors** predict future | $y_t = \\mu + \\theta_1 \\epsilon_{t-1} + ... + \\epsilon_t$ |\n| **ARIMA(p,d,q)** | AR + MA + **differencing** | Combines both, d = differencing order |\n| **SARIMA** | ARIMA + **seasonality** | (p,d,q) × (P,D,Q,s) |\n\n## ARIMA: The Workhorse\n\n$$\ny_t = c + \\underbrace{\\phi_1 y_{t-1} + ... + \\phi_p y_{t-p}}_{\\text{AR: past values}} + \\underbrace{\\theta_1 \\epsilon_{t-1} + ... + \\theta_q \\epsilon_{t-q}}_{\\text{MA: past errors}} + \\epsilon_t\n$$\n\n**ARIMA(p, d, q)**:\n\n- **p** = AR order (how many past values?)\n- **d** = differencing order (how many times to difference?)\n- **q** = MA order (how many past errors?)\n\n## SARIMA: Adding Seasonality\n\nFor data with seasonal patterns, add seasonal terms:\n\n**SARIMA(p,d,q) × (P,D,Q,s)**\n\n- Lowercase (p,d,q) = short-term dynamics\n- Uppercase (P,D,Q) = seasonal dynamics  \n- **s** = seasonal period (12 for monthly, 4 for quarterly)\n\nExample: SARIMA(1,1,1)×(1,1,1,12) for monthly data with yearly seasonality\n\n\n## SARIMA in Practice\n\nLet's forecast air passengers with SARIMA(1,1,1)×(1,1,1,12):\n\n\n\n---\n\n\n\n## Model Diagnostics\n\n::: {#e7784855 .cell execution_count=28}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-29-output-1.png){width=1142 height=566 fig-align='center'}\n:::\n:::\n\n\n**What to check:**\n\n- **Residuals**: Should look like white noise (no pattern)\n- **Histogram**: Should be roughly normal\n- **Q-Q plot**: Points should follow the diagonal\n- **ACF**: No significant spikes (we captured all structure)\n\n---\n\nFinally, let's make a forecast for 2 years out.\n\n::: {#5a3ea670 .cell execution_count=29}\n\n::: {.cell-output .cell-output-display}\n![](26-TimeSeries_files/figure-revealjs/cell-30-output-1.png){width=798 height=485}\n:::\n:::\n\n\nThe light pink area shows the 95% confidence interval for the forecast.\n\n**Question**: What observations do you have about the prediction?\n\n\n# Model Selection & Evaluation\n\n## How Do We Choose Parameters?\n\n**AIC & BIC**: Balance fit vs. complexity\n\n$$\\text{AIC} = T\\log\\left(\\frac{\\text{SSE}}{T}\\right) + 2k \\quad \\text{(lower is better)}$$\n\nwhere $k$ is the number of parameters in the model.\n\n| Criterion | Penalizes complexity... |\n|-----------|------------------------|\n| **AIC** | Moderately |\n| **BIC** | More heavily (prefers simpler models) |\n\nIn practice: try multiple (p,d,q) combinations, pick lowest AIC/BIC.\n\n## Time Series Cross-Validation\n\n⚠️ **Can't shuffle!** Must respect temporal order.\n\n**Rolling forecast origin:**\n\n```\nTrain: [----] Test: [.]\nTrain: [-----] Test: [.]\nTrain: [------] Test: [.]\n```\n\nAlways train on past, test on future — no data leakage!\n\n# Summary\n\n## Key Takeaways\n\n1. **Visualize first** — trends, seasonality, autocorrelation\n2. **Decompose** — separate signal from noise (STL > classical)\n3. **Check stationarity** — transform if needed (differencing, log)\n4. **Model** — ARIMA for non-seasonal, SARIMA for seasonal\n5. **Validate** — diagnostics + time-aware cross-validation\n\n## References\n\n- [Forecasting: Principles & Practice](https://otexts.com/fpp3/) — the definitive free textbook\n- [statsmodels documentation](https://www.statsmodels.org/stable/tsa.html)\n\n## Bibliography\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "26-TimeSeries_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}