---
title: Lecture Schedule
---

> This is a tentative schedule. It is subject to change.

| Date | Lecture | Notes | Homework |
| ---- | ------- | --- | -------- |
| **Week 1**  | --- | --- | --- |
| Sep 2 | 01 -- Course Intro and Git | [Class Intro](./00-Class-Introduction.qmd), [Git](./02A-Git.qmd)  | |
| Sep 4 | 02 -- Spark Project Pitch Day | [Pitch Deck](https://docs.google.com/presentation/d/1PuVoX9xIwi5x6FkJBvtjwj6tQ-Fp2WDdmj7ESr1_ESU/edit?slide=id.g3652bfb82da_1_27#slide=id.g3652bfb82da_1_27) |  |
| **Week 2**  | --- | --- | --- |
| Sep 9 | 03 -- Class Survey Results, Intro to Pandas | [Survey Results (1)](https://docs.google.com/presentation/d/e/2PACX-1vS9da4EjD0vZ0--eIwYKMrNz7YlFKKsfe7QjpyhnVUT-DfpotVsjcL_H8z6vVkzW0k1v2Xxd2bakIDc/pub?start=false&loop=false&delayms=3000&slide=id.p), [Pandas](./02B-Pandas.qmd)<br> (1) BU email address required  | |
| Sep 11 | 04 -- DS Project Lifecycle, Intro to SciKit-Learn | [DS PLC](https://docs.google.com/presentation/d/e/2PACX-1vTLyHd8UIU94ayKf17KIHdOYBNkEBJ6F0P5NMRRuJt5v0pioCVdEUpSVBvBc67mikJsVj7ijTCoqPh2/pub?start=false&loop=false&delayms=3000), [SciKit-Learn](./02C-Sklearn.qmd)  | |
| **Week 3**  | --- | --- | --- |
| Sep 16 | 05 -- Probability Refresher | [Probability](./03-Probability-and-Statistics-Refresher.qmd) |  |
| Sep 18 | 06 -- Linear Algebra Refresher | [Linear Algebra](./04-Linear-Algebra-Refresher.qmd)   | |
| **Week 4**  | --- | --- | --- |
| Sep 23 | 07 -- Distance, Similarity Functions and Time Series  | [Distances, Time Series](./05-Distances-Timeseries.qmd)   | |
| Sep 25 | 08 -- Clustering I: k-means | [k-means](./06-Clustering-I-kmeans.qmd) | |
| **Week 5**  | --- | --- | --- |
| Sep 30 | 09 -- Clusterin II: In Practice |  [Clustering in Practice](./07-Clustering-II-in-practice.qmd)  |  |
| Oct 2 | 10 -- Clustering III: Hierarchical |  [Hierarchical Clustering](./08-Clustering-III-hierarchical.qmd)  |  |
| **Week 6**  | --- | --- | --- |
| Oct 7 | 11 -- Clustering IV: GMM and Expectation Maximization | [GMM and EM](./09-Clustering-IV-GMM-EM.qmd)  | |
| Oct 9|  12 -- Learning From Data | [Learning From Data](./13-Learning-From-Data.qmd) |  |
| **Week 7**  | --- | --- | --- |
| Oct 14 | _🍂 No Class -- Monday Schedule_ 🍂 |   |  |
| Oct 16 | 13 -- Classification I: Decision Trees and Random Forests | [Decision Trees](./14-Classification-I-Decision-Trees.qmd) |  |
| **Week 8**  | --- | --- | --- |
| Oct 21 | 14 -- Classification II: k-Nearest Neighbors | [k-NN](./15-Classification-II-kNN.qmd)  | |
| Oct 23 | 15 -- Linear Regression | [Linear Regression](./17-Regression-I-Linear.qmd)  | |
| **Week 9**  | --- | --- | --- |
| Oct 28 | 16 -- Logistic Regression and Regularization | [Logistic Regression](./18-Regression-II-Logistic.qmd) [Regularization](./19-Regression-III-More-Linear.qmd) | |
| Oct 30 | 17  -- SVD Low Rank Approximations | [SVD](./10-Low-Rank-and-SVD.qmd)  |  |
| **Week 10**  | --- | --- | --- |
| Nov 4 | 18 -- Dimensionality Reduction: PCA and t-SNE | [PCA and t-SNE](./11-Dimensionality-Reduction-SVD-II.qmd)  | |
| Nov 6 | 19 -- Neural Networks: Gradient Descent & Backpropagation | [NN I](./23-NN-I-Gradient-Descent.qmd), [NN II](./24-NN-II-Backprop.qmd) | |
| **Week 11**  | --- | --- | --- |
| Nov 11 | 20 -- Intro to NLP | [NLP](./28-NLP.qmd) 
| Nov 13 | 21 -- Recommender Systems | [Recommender Systems](./20-Recommender-Systems.qmd)  | |
| **Week 12**  | --- | --- | --- |
| Nov 18 | 22  -- Graphs I| [Graphs I](./21-Networks-I.qmd) | |
| Nov 20 | 23 -- Graphs II | [Graphs II](./22-Networks-II-Centrality-Clustering.qmd)  | |
| **Week 13**  | --- | --- | --- |
| Nov 25 | 24 -- Time Series Analysis | [Time Series](./26-TimeSeries.qmd) | |
| Nov 27 | 🦃 _No Class -- Thanksgiving Recess_ 🌽 |  | |
| **Week 14**  | --- | --- | --- |
| Dec 2 | 25 -- Lecture to be announced |   | |
| Dec 4 | 📽️ _Project Presentation I_ 📽️| |  |
| **Week 15**  | --- | --- | --- |
| Dec 9 | 📽️ _Project Presentations II_ 📽️ |   | |
| Dec 10 | 🎉 _Last Day of Classes_ 🎉 | 🔬 Projects Due 🔬  | |
| Dec 11 | ✨  Spark Demo Day 4pm -- 7pm ⚡️ |  |  |

<!-- | --- | 14 -- Classification III: Naive Bayes and SVM | [Naive Bayes and SVM](./16-Classification-III-NB-SVM.qmd) |  | -->
<!-- | Nov 4 | 20 -- Neural Networks II: Backpropagation | [NN II](./24-NN-II-Backprop.qmd)   | | -->
<!-- | Nov 6 | 21 -- Neural Networks III: CNNs | [NN III](./25-NN-III-CNNs.qmd) |  | -->