---
title: Clustering Topics Outline
---

## Current Topics

### Clustering I:  k-Means Clustering

1. Solving Cholera Outbreak
2. Applications of Clustering
3. The clustering problem
4. **k-mean Algorithm**
5. **Feature Scaling**
6. Application: Image palletization

### Clustering II: Clustering in Practice

1. Synthetic Data Example
2. Dimensionality reduction and visualization with **MDS**
3. Cluster Evaluation
    1. with ground truth data
        1. **Rand Index** and **ARI**
    2. k-means objective function and choosing # of clusters
    3. without ground truth data?
        1. **Silhouette Coefficient**
4. Real Data -- 20 Newsgroups
    1. Feature Extraction
    2. Exploratory Data Analysis
    3. Selecting # of clusters
    4. Visualization of results

### Clustering III: Hierarchical

1. **Hierarchical Clustering**
    1. Strengths
    2. Comparison to k-means
2. Hierarchical Clustering Algos
    1. Types
        1. **Agglomerative (bottom-up)**
        2. **Divisive (top-down)**
3. Defining Cluster Proximity
4. **Single-Linkage Clustering**
5. **Complete-Linkage Clustering**
6. **Average-Linkage Clustering**
7. All three compared
8. **Ward's Distance**
9. Hierarchical Clustering in Practice

### Clustering IV: Soft Clustering with Gaussian Mixture Models

1. From Hard to Soft Clustering
2. **Mixture of Gaussians**
3. Learning parameters of a GMM
4. Probabilities
5. **EM for GMM**
6. Instantiating EM with GMM