project:
  output-dir: _revealjs
  pre-render: print_quarto_config.py
  render:
    - 00-Class-Introduction.qmd
    - 01-Intro-to-Python.qmd
    - 02A-Git.qmd
    - 02B-Pandas.qmd
    - 02C-Sklearn.qmd
    - 03-Probability-and-Statistics-Refresher.qmd
    - 04-Linear-Algebra-Refresher.qmd
    - 05-Distances-Timeseries.qmd
    - 05A-Learning.qmd
    - 06-Clustering-I-kmeans.qmd
    - 07-Clustering-II-in-practice.qmd
    - 08-Clustering-III-hierarchical.qmd
    - 09-Clustering-IV-GMM-EM.qmd
    - 09A-Appendix-Derive-MLE-params-for-gaussian.qmd
    - 09B-Appendix-Cov-Matrix-in-MV-Gaussians.qmd
    - 10-Low-Rank-and-SVD.qmd
    - 11-Dimensionality-Reduction-SVD-II.qmd
    - 12-Anomaly-Detection-SVD-III.qmd
    - 13-Learning-From-Data.qmd
    - 14-Classification-I-Decision-Trees.qmd
    - 15-Classification-II-kNN.qmd
    - 16-Classification-III-NB-SVM.qmd
    - 17-Regression-I-Linear.qmd
    - 18-Regression-II-Logistic.qmd
    - 19-Regression-III-More-Linear.qmd
    - 20-Recommender-Systems.qmd
    - 21-Networks-I.qmd
    - 22-Networks-II-Centrality-Clustering.qmd
    - 23-NN-I-Gradient-Descent.qmd
    - 24-NN-II-Backprop.qmd
    - 25-NN-III-CNNs.qmd
    - 26-TimeSeries.qmd
    - 27-RNN.qmd
    - 28-NLP.qmd

resources:
  - figs/NN-figs/conv-demo/index.html
  - figs/NN-figs/conv-demo/utils.js
  - figs/NN-figs/conv-demo/external/d3.min.js

format:
  revealjs:
    footer: "DS701 -- Fall 2025 -- Gardos"
    scrollable: true
    slide-number: c/t
    center: false
    show-slide-number: all
    chalkboard: true
    smaller: true
    html-math-method: mathjax
    echo: true
    code-fold: true
    css: styles.css
    # eventually I think we want to use this option but I don't want
    # to enable it so late in the semester since it will effect all
    # the earlier slides. See
    # https://quarto.org/docs/presentations/revealjs/advanced.html#stretch
    auto-stretch: false


execute: 
  freeze: auto # see https://quarto.org/docs/projects/code-execution.html#freeze
  cache: true  # see https://quarto.org/docs/projects/code-execution.html#cache
